from database.models.government.department import Department
from database.models.government.designation import Designation
from database.models.government.office import Office
from database.models.government.officer import Officer
from database.models.government.posting import Posting
from database.models.government.transfer import Transfer
from database.models.government.promotion import Promotion
from database.models.government.leave import Leave
from database.models.government.suspension import Suspension
from .retirement import Retirement
from .training import Training