"""add ward table

Revision ID: 062b4185b355
Revises: 9db4ff10ab72
Create Date: 2026-08-02 22:29:32.343686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062b4185b355'
down_revision: Union[str, Sequence[str], None] = '9db4ff10ab72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('ward_name', sa.String(length=150), nullable=False),
    sa.Column('ward_number', sa.Integer(), nullable=False),
    sa.Column('municipal_body_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['municipal_body_id'], ['municipal_bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_id'), 'wards', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_wards_id'), table_name='wards')
    op.drop_table('wards')
    # ### end Alembic commands ###
