"""add locality table

Revision ID: 237b6ecf6368
Revises: 062b4185b355
Create Date: 2026-08-03 13:52:39.056686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237b6ecf6368'
down_revision: Union[str, Sequence[str], None] = '062b4185b355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('locality_name', sa.String(length=150), nullable=False),
    sa.Column('locality_code', sa.String(length=30), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locality_code')
    )
    op.create_index(op.f('ix_localities_id'), 'localities', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_localities_id'), table_name='localities')
    op.drop_table('localities')
    # ### end Alembic commands ###
