"""add citizen urban location mapping

Revision ID: 37f6f3bd1789
Revises: ea50ea5fe3ef
Create Date: 2026-08-24 02:16:50.185600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f6f3bd1789'
down_revision: Union[str, Sequence[str], None] = 'ea50ea5fe3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    inspector = sa.inspect(bind)
    columns = {
        column["name"]
        for column in inspector.get_columns("citizens")
    }

    with op.batch_alter_table(
        "citizens",
        recreate="always",
    ) as batch_op:

        if "municipal_body_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "municipal_body_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "ward_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "ward_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "locality_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "locality_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        batch_op.create_foreign_key(
            "fk_citizens_municipal_body_id",
            "municipal_bodies",
            ["municipal_body_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_citizens_ward_id",
            "wards",
            ["ward_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_citizens_locality_id",
            "localities",
            ["locality_id"],
            ["id"],
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citizens', type_='foreignkey')
    op.drop_constraint(None, 'citizens', type_='foreignkey')
    op.drop_constraint(None, 'citizens', type_='foreignkey')
    op.drop_column('citizens', 'locality_id')
    op.drop_column('citizens', 'ward_id')
    op.drop_column('citizens', 'municipal_body_id')
    # ### end Alembic commands ###
