"""add complaint module

Revision ID: 40a0264405ac
Revises: 3ba04f94eaf7
Create Date: 2026-08-01 14:08:45.235484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a0264405ac'
down_revision: Union[str, Sequence[str], None] = '3ba04f94eaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_levels',
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('level_code', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_code'),
    sa.UniqueConstraint('level_name')
    )
    op.create_index(op.f('ix_administrative_levels_id'), 'administrative_levels', ['id'], unique=False)
    op.create_table('complaint_categories',
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code'),
    sa.UniqueConstraint('category_name')
    )
    op.create_index(op.f('ix_complaint_categories_id'), 'complaint_categories', ['id'], unique=False)
    op.create_table('complaint_priorities',
    sa.Column('priority_name', sa.String(length=50), nullable=False),
    sa.Column('priority_code', sa.String(length=20), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_code'),
    sa.UniqueConstraint('priority_name')
    )
    op.create_index(op.f('ix_complaint_priorities_id'), 'complaint_priorities', ['id'], unique=False)
    op.create_table('complaint_statuses',
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('allow_reopen', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code'),
    sa.UniqueConstraint('status_name')
    )
    op.create_index(op.f('ix_complaint_statuses_id'), 'complaint_statuses', ['id'], unique=False)
    op.create_table('complaint_category_mappings',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('administrative_level_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['administrative_level_id'], ['administrative_levels.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['complaint_priorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_category_mappings_id'), 'complaint_category_mappings', ['id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_number', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('is_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['complaint_priorities.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['complaint_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_number')
    )
    op.create_index(op.f('ix_complaints_id'), 'complaints', ['id'], unique=False)
    op.create_table('complaint_assignments',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_officer_id', sa.Integer(), nullable=True),
    sa.Column('assignment_status', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_assignments_id'), 'complaint_assignments', ['id'], unique=False)
    op.create_table('complaint_attachments',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_officer_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_attachments_id'), 'complaint_attachments', ['id'], unique=False)
    op.create_table('complaint_escalations',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('from_officer_id', sa.Integer(), nullable=True),
    sa.Column('to_officer_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['from_officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['to_officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_escalations_id'), 'complaint_escalations', ['id'], unique=False)
    op.create_table('complaint_feedbacks',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.String(length=1000), nullable=True),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_feedbacks_id'), 'complaint_feedbacks', ['id'], unique=False)
    op.create_table('complaint_otps',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_otps_id'), 'complaint_otps', ['id'], unique=False)
    op.create_table('complaint_timelines',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device_info', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['complaint_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_timelines_id'), 'complaint_timelines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_timelines_id'), table_name='complaint_timelines')
    op.drop_table('complaint_timelines')
    op.drop_index(op.f('ix_complaint_otps_id'), table_name='complaint_otps')
    op.drop_table('complaint_otps')
    op.drop_index(op.f('ix_complaint_feedbacks_id'), table_name='complaint_feedbacks')
    op.drop_table('complaint_feedbacks')
    op.drop_index(op.f('ix_complaint_escalations_id'), table_name='complaint_escalations')
    op.drop_table('complaint_escalations')
    op.drop_index(op.f('ix_complaint_attachments_id'), table_name='complaint_attachments')
    op.drop_table('complaint_attachments')
    op.drop_index(op.f('ix_complaint_assignments_id'), table_name='complaint_assignments')
    op.drop_table('complaint_assignments')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_complaint_category_mappings_id'), table_name='complaint_category_mappings')
    op.drop_table('complaint_category_mappings')
    op.drop_index(op.f('ix_complaint_statuses_id'), table_name='complaint_statuses')
    op.drop_table('complaint_statuses')
    op.drop_index(op.f('ix_complaint_priorities_id'), table_name='complaint_priorities')
    op.drop_table('complaint_priorities')
    op.drop_index(op.f('ix_complaint_categories_id'), table_name='complaint_categories')
    op.drop_table('complaint_categories')
    op.drop_index(op.f('ix_administrative_levels_id'), table_name='administrative_levels')
    op.drop_table('administrative_levels')
    # ### end Alembic commands ###
