"""create reference module

Revision ID: 91e4333df839
Revises: 237b6ecf6368
Create Date: 2026-08-05 14:46:20.480626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e4333df839'
down_revision: Union[str, Sequence[str], None] = '237b6ecf6368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_types',
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_code'),
    sa.UniqueConstraint('module_name')
    )
    op.create_index(op.f('ix_reference_types_id'), 'reference_types', ['id'], unique=False)
    op.create_table('reference_formats',
    sa.Column('reference_type_id', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('separator', sa.String(length=5), nullable=False),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reference_type_id'], ['reference_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_formats_id'), 'reference_formats', ['id'], unique=False)
    op.create_table('reference_sequences',
    sa.Column('reference_format_id', sa.Integer(), nullable=False),
    sa.Column('sequence_period', sa.String(length=30), nullable=False),
    sa.Column('period_value', sa.String(length=30), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reference_format_id'], ['reference_formats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_sequences_id'), 'reference_sequences', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_reference_sequences_id'), table_name='reference_sequences')
    op.drop_table('reference_sequences')
    op.drop_index(op.f('ix_reference_formats_id'), table_name='reference_formats')
    op.drop_table('reference_formats')
    op.drop_index(op.f('ix_reference_types_id'), table_name='reference_types')
    op.drop_table('reference_types')
    # ### end Alembic commands ###
