"""add complaint subcategory and mapping

Revision ID: 979ece5bf9e8
Revises: 40a0264405ac
Create Date: 2026-08-01 14:57:16.120129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979ece5bf9e8'
down_revision: Union[str, Sequence[str], None] = '40a0264405ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_subcategories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_name', sa.String(length=150), nullable=False),
    sa.Column('subcategory_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_code')
    )
    op.create_index(op.f('ix_complaint_subcategories_id'), 'complaint_subcategories', ['id'], unique=False)
    op.create_table('complaint_subcategory_mappings',
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('administrative_level_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['administrative_level_id'], ['administrative_levels.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['complaint_priorities.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['complaint_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_subcategory_mappings_id'), 'complaint_subcategory_mappings', ['id'], unique=False)
    with op.batch_alter_table(
        "complaints",
        recreate="always",
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subcategory_id",
                sa.Integer(),
                nullable=False,
            )
        )

        batch_op.create_foreign_key(
            "fk_complaints_subcategory_id",
            "complaint_subcategories",
            ["subcategory_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "complaints",
        recreate="always",
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_complaints_subcategory_id",
            type_="foreignkey",
        )
        batch_op.drop_column(
            "subcategory_id"
        )
    op.drop_index(op.f('ix_complaint_subcategory_mappings_id'), table_name='complaint_subcategory_mappings')
    op.drop_table('complaint_subcategory_mappings')
    op.drop_index(op.f('ix_complaint_subcategories_id'), table_name='complaint_subcategories')
    op.drop_table('complaint_subcategories')
    # ### end Alembic commands ###
