"""add municipal bodies table

Revision ID: 9db4ff10ab72
Revises: 979ece5bf9e8
Create Date: 2026-08-02 21:10:26.490127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db4ff10ab72'
down_revision: Union[str, Sequence[str], None] = '979ece5bf9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_bodies',
    sa.Column('body_name', sa.String(length=150), nullable=False),
    sa.Column('body_code', sa.String(length=20), nullable=False),
    sa.Column('body_type', sa.Enum('NAGAR_NIGAM', 'NAGAR_PALIKA_PARISHAD', 'NAGAR_PANCHAYAT', name='municipalbodytype'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('headquarters', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body_code'),
    sa.UniqueConstraint('body_name')
    )
    op.create_index(op.f('ix_municipal_bodies_id'), 'municipal_bodies', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_municipal_bodies_id'), table_name='municipal_bodies')
    op.drop_table('municipal_bodies')
    # ### end Alembic commands ###
