"""add pending citizen registration otp

Revision ID: d26ecc4387d3
Revises: 37f6f3bd1789
Create Date: 2026-08-24 12:08:35.215061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26ecc4387d3'
down_revision: Union[str, Sequence[str], None] = '37f6f3bd1789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create pending citizen registration OTP table."""
    op.create_table(
        "pending_citizen_registrations",

        sa.Column(
            "full_name",
            sa.String(150),
            nullable=False,
        ),

        sa.Column(
            "username",
            sa.String(100),
            nullable=False,
        ),

        sa.Column(
            "email",
            sa.String(150),
            nullable=False,
        ),

        sa.Column(
            "mobile",
            sa.String(20),
            nullable=False,
        ),

        sa.Column(
            "password_hash",
            sa.String(255),
            nullable=False,
        ),

        sa.Column(
            "father_name",
            sa.String(150),
            nullable=True,
        ),

        sa.Column(
            "mother_name",
            sa.String(150),
            nullable=True,
        ),

        sa.Column(
            "gender",
            sa.String(20),
            nullable=True,
        ),

        sa.Column(
            "dob",
            sa.Date(),
            nullable=True,
        ),

        sa.Column(
            "address",
            sa.Text(),
            nullable=False,
        ),

        sa.Column(
            "pincode",
            sa.String(10),
            nullable=True,
        ),

        sa.Column(
            "state_id",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "district_id",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "area_type",
            sa.String(20),
            nullable=False,
        ),

        sa.Column(
            "tehsil_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "block_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "gram_panchayat_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "village_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "municipal_body_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "ward_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "locality_id",
            sa.Integer(),
            nullable=True,
        ),

        sa.Column(
            "otp_hash",
            sa.String(128),
            nullable=True,
        ),

        sa.Column(
            "otp_expires_at",
            sa.DateTime(),
            nullable=True,
        ),

        sa.Column(
            "otp_attempts",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),

        sa.Column(
            "last_otp_sent_at",
            sa.DateTime(),
            nullable=True,
        ),

        sa.Column(
            "id",
            sa.Integer(),
            primary_key=True,
            autoincrement=True,
        ),

        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
        ),

        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
        ),

        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    """Drop pending citizen registration OTP table."""
    op.drop_table(
        "pending_citizen_registrations"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
