"""add office urban geographic mapping

Revision ID: ea50ea5fe3ef
Revises: f3148b680c32
Create Date: 2026-08-24 01:43:16.419284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea50ea5fe3ef'
down_revision: Union[str, Sequence[str], None] = 'f3148b680c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    inspector = sa.inspect(bind)
    columns = {
        column["name"]
        for column in inspector.get_columns("offices")
    }

    with op.batch_alter_table(
        "offices",
        recreate="always",
    ) as batch_op:

        if "municipal_body_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "municipal_body_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "ward_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "ward_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "locality_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "locality_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        batch_op.create_foreign_key(
            "fk_offices_municipal_body_id",
            "municipal_bodies",
            ["municipal_body_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_offices_ward_id",
            "wards",
            ["ward_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_offices_locality_id",
            "localities",
            ["locality_id"],
            ["id"],
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_column('offices', 'locality_id')
    op.drop_column('offices', 'ward_id')
    op.drop_column('offices', 'municipal_body_id')
    # ### end Alembic commands ###
