"""add office geographic mapping

Revision ID: f3148b680c32
Revises: 313b1769bb77
Create Date: 2026-08-24 01:30:09.490607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3148b680c32'
down_revision: Union[str, Sequence[str], None] = '313b1769bb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    inspector = sa.inspect(bind)
    columns = {
        column["name"]
        for column in inspector.get_columns("offices")
    }

    with op.batch_alter_table(
        "offices",
        recreate="always",
    ) as batch_op:

        if "district_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "district_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "tehsil_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "tehsil_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        if "block_id" not in columns:
            batch_op.add_column(
                sa.Column(
                    "block_id",
                    sa.Integer(),
                    nullable=True,
                )
            )

        batch_op.create_foreign_key(
            "fk_offices_district_id",
            "districts",
            ["district_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_offices_tehsil_id",
            "tehsils",
            ["tehsil_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_offices_block_id",
            "blocks",
            ["block_id"],
            ["id"],
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_column('offices', 'block_id')
    op.drop_column('offices', 'tehsil_id')
    op.drop_column('offices', 'district_id')
    # ### end Alembic commands ###
